// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

const { readFileSync } = require('node:fs');

const REPOSITORY = 'dotnet/spark';
const STATUS_BRANCH = 'ci-status';
const PROJECT_ID = '1d09b833-a6f2-4fab-8ec0-b2bf075dcd70';
const APP_ID = 9426;
const PIPELINE_ID = 51729;
const OWNER_MARKER = 'Generated by dotnet/spark CI status publisher (schema 1).\n';
const REPO = { owner: 'dotnet', repo: 'spark' };

function readMatrix(yaml) {
    function values(name) {
        const lines = yaml.split(/\r?\n/);
        const start = lines.indexOf(`- name: ${name}`);
        if (start < 0) throw new Error(`Missing pipeline parameter: ${name}`);
        if (lines.filter(line => line === `- name: ${name}`).length !== 1) {
            throw new Error(`Duplicate pipeline parameter: ${name}`);
        }
        const result = [];
        let inDefault = false;
        for (const line of lines.slice(start + 1)) {
            if (line === '  default:') {
                inDefault = true;
            } else if (inDefault) {
                const match = /^  - ['"]([^'"]+)['"]\s*$/.exec(line);
                if (match) result.push(match[1]);
                else if (line.trim() && !line.trim().startsWith('#')) {
                    if (/^\s/.test(line)) throw new Error(`Unsupported pipeline parameter entry: ${line}`);
                    break;
                }
            }
        }
        if (!result.length || new Set(result).size !== result.length) {
            throw new Error(`Empty or duplicate pipeline parameter: ${name}`);
        }
        return result;
    }
    const versions = values('listOfE2ETestsSparkVersions');
    const platforms = values('listOfE2ETestsPoolTypes');
    if (versions.some(version => !/^\d+\.\d+\.\d+$/.test(version)) ||
        platforms.join(',') !== 'Windows,Linux') {
        throw new Error('Unsupported E2E matrix format; update the status publisher.');
    }
    return { versions, platforms };
}

function buildId(run, sha) {
    if (run.app?.id !== APP_ID || run.app?.slug !== 'azure-pipelines' ||
        run.head_sha !== sha || !Number.isSafeInteger(run.id) ||
        !(run.name === 'spark.net' || run.name?.startsWith('spark.net ('))) return null;
    const match = new RegExp(`^${PIPELINE_ID}\\|(\\d+)\\|${PROJECT_ID}$`).exec(run.external_id);
    const id = match && Number(match[1]);
    return Number.isSafeInteger(id) && id > 0 ? id : null;
}

function result(run, finished) {
    const conclusions = {
        success: ['passing', '#4c1'],
        failure: ['failing', '#e05d44'],
        timed_out: ['timed out', '#e05d44'],
        cancelled: ['cancelled', '#9f9f9f'],
        skipped: ['skipped', '#9f9f9f'],
        neutral: ['neutral', '#9f9f9f'],
        stale: ['stale', '#9f9f9f'],
        action_required: ['action required', '#dfb317']
    };
    const activeStates = {
        queued: ['queued', '#dfb317'],
        pending: ['pending', '#dfb317'],
        waiting: ['waiting', '#dfb317'],
        requested: ['requested', '#dfb317'],
        in_progress: ['running', '#007ec6']
    };
    let display;
    if (!run) display = finished ? ['not reported', '#9f9f9f'] : ['pending', '#dfb317'];
    else if (run.status === 'completed') {
        // A missing or unrecognized conclusion must never become a green badge.
        display = Object.hasOwn(conclusions, run.conclusion) ? conclusions[run.conclusion] : ['unknown', '#9f9f9f'];
    } else display = Object.hasOwn(activeStates, run.status) ? activeStates[run.status] : ['unknown', '#9f9f9f'];
    return {
        message: display[0], color: display[1],
        checkId: run?.id ?? null,
        status: run?.status ?? null, conclusion: run?.conclusion ?? null,
        startedAt: run?.started_at ?? null, completedAt: run?.completed_at ?? null
    };
}

function createSnapshot(sha, matrix, runs) {
    if (!/^[a-f0-9]{40}$/.test(sha)) throw new Error('Invalid source commit.');
    const eligible = runs.filter(run => buildId(run, sha) !== null);
    // Build IDs order builds; check IDs only order reports within the same build.
    const latestBuild = eligible.reduce((latest, run) => Math.max(latest, buildId(run, sha)), 0);
    const latest = new Map();
    for (const run of eligible) {
        if (buildId(run, sha) === latestBuild && run.id > (latest.get(run.name)?.id ?? 0)) {
            latest.set(run.name, run);
        }
    }
    const summary = latest.get('spark.net');
    return {
        schemaVersion: 1, repository: REPOSITORY, branch: 'main', headSha: sha,
        pipelineId: PIPELINE_ID, buildId: latestBuild || null,
        overall: result(summary, false),
        jobs: matrix.versions.flatMap(version => matrix.platforms.map(platform => ({
            version, platform,
            ...result(latest.get(`spark.net (E2E tests for Spark ${version} Run_${platform})`),
                summary?.status === 'completed')
        })))
    };
}

async function collectSnapshot(github, sha, matrix) {
    const suites = await github.paginate(github.rest.checks.listSuitesForRef, {
        ...REPO, ref: sha, app_id: APP_ID, per_page: 100
    });
    const runs = [];
    for (const suite of suites) {
        if (suite.app?.id === APP_ID && suite.app?.slug === 'azure-pipelines' &&
            suite.head_branch === 'main' && suite.head_sha === sha) {
            runs.push(...await github.paginate(github.rest.checks.listForSuite, {
                ...REPO, check_suite_id: suite.id, filter: 'all', per_page: 100
            }));
        }
    }
    return createSnapshot(sha, matrix, runs);
}

function escapeXml(text) {
    return String(text).replace(/[&<>"']/g, char => ({
        '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&apos;'
    })[char]);
}

function renderBadge(label, state, snapshot) {
    const left = Math.ceil(label.length * 6.8 + 12);
    const right = Math.ceil(state.message.length * 6.8 + 12);
    const title = `${label}: ${state.message} — main@${snapshot.headSha}; build ${snapshot.buildId ?? 'pending'}`;
    return `<svg xmlns="http://www.w3.org/2000/svg" width="${left + right}" height="20" role="img" aria-label="${escapeXml(title)}">
<title>${escapeXml(title)}</title>
<clipPath id="r"><rect width="${left + right}" height="20" rx="3"/></clipPath>
<g clip-path="url(#r)"><rect width="${left}" height="20" fill="#555"/><rect x="${left}" width="${right}" height="20" fill="${state.color}"/></g>
<g fill="#fff" text-anchor="middle" font-family="Verdana,DejaVu Sans,sans-serif" font-size="11">
<text x="${left / 2}" y="14">${escapeXml(label)}</text><text x="${left + right / 2}" y="14">${escapeXml(state.message)}</text></g>
</svg>\n`;
}

function renderFiles(snapshot) {
    const files = {
        '.ci-status-owner': OWNER_MARKER,
        'status.json': `${JSON.stringify(snapshot, null, 2)}\n`,
        'badges/main.svg': renderBadge('Azure Pipelines (main)', snapshot.overall, snapshot),
        'badges/revision.svg': renderBadge('main', {
            message: snapshot.headSha.slice(0, 7), color: '#007ec6'
        }, snapshot)
    };
    const buildUrl = `https://msasg.visualstudio.com/ManagedOSS/_build/results?buildId=${snapshot.buildId}`;
    const lines = [
        '# Azure Pipelines status snapshot', '',
        `Source: [main@${snapshot.headSha.slice(0, 7)}](https://github.com/${REPOSITORY}/commit/${snapshot.headSha}).`, '',
        snapshot.buildId ? `Azure pipeline 51729, [build ${snapshot.buildId}](${buildUrl}).` : 'Waiting for Azure pipeline 51729 to report checks.', '',
        'This machine-owned branch contains cached GitHub Checks results, not build logs. Do not edit it manually.', '',
        'The publisher runs on main pushes, periodically, and on eligible check-suite completion events. No-change refreshes do not create commits. See [publisher runs](https://github.com/dotnet/spark/actions/workflows/ci-status.yml) for refresh failures and timings.', '',
        '![Overall status](badges/main.svg)', '',
        '| Spark | Windows | Linux |', '| :--- | :--- | :--- |'
    ];
    function checkLink(job) {
        return job.checkId ? `[${job.message}](https://github.com/${REPOSITORY}/runs/${job.checkId})` : job.message;
    }
    for (const version of [...new Set(snapshot.jobs.map(job => job.version))]) {
        const jobs = snapshot.jobs.filter(job => job.version === version);
        lines.push(`| ${version} | ${jobs.map(checkLink).join(' | ')} |`);
        for (const job of jobs) {
            files[`badges/spark-${version}-${job.platform.toLowerCase()}.svg`] = renderBadge(job.platform, job, snapshot);
        }
    }
    files['README.md'] = `${lines.join('\n')}\n`;
    return files;
}

async function mainSha(github) {
    return (await github.rest.git.getRef({ ...REPO, ref: 'heads/main' })).data.object.sha;
}

async function publishSnapshot(github, snapshot, files) {
    let previous;
    try {
        previous = (await github.rest.git.getRef({ ...REPO, ref: `heads/${STATUS_BRANCH}` })).data.object.sha;
    } catch (error) {
        if (error.status !== 404) throw error;
    }
    let baseTree;
    if (previous) {
        const marker = (await github.rest.repos.getContent({
            ...REPO, path: '.ci-status-owner', ref: previous
        })).data;
        if (marker.type !== 'file' || marker.encoding !== 'base64' ||
            Buffer.from(marker.content, 'base64').toString('utf8') !== OWNER_MARKER) {
            throw new Error('Refusing to publish to a ci-status branch not owned by this publisher.');
        }
        baseTree = (await github.rest.git.getCommit({ ...REPO, commit_sha: previous })).data.tree.sha;
    }
    const tree = (await github.rest.git.createTree({
        ...REPO, ...(baseTree ? { base_tree: baseTree } : {}),
        tree: Object.entries(files).map(([path, content]) => ({ path, mode: '100644', type: 'blob', content }))
    })).data.sha;
    if (tree === baseTree) return 'unchanged';

    // A run for an older checkout must not replace a newer main snapshot.
    if (await mainSha(github) !== snapshot.headSha) return 'main moved; skipped';
    const commit = (await github.rest.git.createCommit({
        ...REPO, message: `Update CI status for ${snapshot.headSha.slice(0, 7)} (build ${snapshot.buildId ?? 'pending'})`,
        tree, parents: previous ? [previous] : []
    })).data.sha;
    if (await mainSha(github) !== snapshot.headSha) return 'main moved; skipped';
    if (previous) {
        await github.rest.git.updateRef({ ...REPO, ref: `heads/${STATUS_BRANCH}`, sha: commit, force: false });
    } else {
        await github.rest.git.createRef({ ...REPO, ref: `refs/heads/${STATUS_BRANCH}`, sha: commit });
    }
    return 'published';
}

async function run({ github, context, core, sourceSha }) {
    if (`${context.repo.owner}/${context.repo.repo}` !== REPOSITORY || context.ref !== 'refs/heads/main') {
        throw new Error('CI status publication is restricted to dotnet/spark main.');
    }
    if (await mainSha(github) !== sourceSha) {
        core.notice('Main moved since checkout; the next refresh will collect its checks.');
        return;
    }
    const matrix = readMatrix(readFileSync('azure-pipelines-pr.yml', 'utf8'));
    const snapshot = await collectSnapshot(github, sourceSha, matrix);
    const outcome = await publishSnapshot(github, snapshot, renderFiles(snapshot));
    core.info(`CI status: ${outcome}; ${snapshot.jobs.length} E2E jobs for main@${sourceSha.slice(0, 7)}.`);
}

module.exports = { readMatrix, createSnapshot, collectSnapshot, renderBadge, renderFiles, publishSnapshot, run };
