// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

const assert = require('node:assert/strict');
const { readFileSync } = require('node:fs');
const path = require('node:path');
const test = require('node:test');
const {
    readMatrix, createSnapshot, collectSnapshot, renderBadge, renderFiles, publishSnapshot, run
} = require('./index.cjs');

const ROOT = path.resolve(__dirname, '../..');
const SHA = 'a'.repeat(40);
const OTHER_SHA = 'b'.repeat(40);
const APP = { id: 9426, slug: 'azure-pipelines' };
const PROJECT = '1d09b833-a6f2-4fab-8ec0-b2bf075dcd70';
const MATRIX = { versions: ['4.0.4'], platforms: ['Windows', 'Linux'] };
const PIPELINE = readFileSync(path.join(ROOT, 'azure-pipelines-pr.yml'), 'utf8');
const OWNER_MARKER = 'Generated by dotnet/spark CI status publisher (schema 1).\n';

function matrixYaml(versions = ["'4.0.4'"], platforms = ["'Windows'", "'Linux'"]) {
    return [
        'parameters:', '- name: listOfE2ETestsSparkVersions', '  type: object', '  default:',
        ...versions.map(version => `  - ${version}`), '',
        '- name: listOfE2ETestsPoolTypes', '  type: object', '  default:',
        ...platforms.map(platform => `  - ${platform}`), '', 'stages:', '  - stage: test'
    ].join('\n');
}

function check(overrides = {}, build = 200) {
    return {
        id: 100, app: APP, head_sha: SHA, name: 'spark.net',
        external_id: `51729|${build}|${PROJECT}`,
        status: 'completed', conclusion: 'success',
        started_at: '2026-09-17T00:00:00Z', completed_at: '2026-09-17T00:10:00Z',
        ...overrides
    };
}

function job(version, platform, overrides = {}, build = 200) {
    return check({ name: `spark.net (E2E tests for Spark ${version} Run_${platform})`, ...overrides }, build);
}

test('matrix parser reads the current 27 x 2 pipeline matrix', () => {
    const matrix = readMatrix(PIPELINE);
    assert.equal(matrix.versions.length, 27);
    assert.equal(new Set(matrix.versions).size, 27);
    assert.deepEqual(matrix.platforms, ['Windows', 'Linux']);
    assert.deepEqual(matrix.versions.slice(-5), ['4.0.0', '4.0.1', '4.0.2', '4.0.3', '4.0.4']);
    assert.deepEqual(readMatrix(matrixYaml().replaceAll('\n', '\r\n')), MATRIX);
    assert.deepEqual(readMatrix(matrixYaml(['"4.0.4"'])), MATRIX);
});

test('matrix parser rejects unsupported or partial configurations', async t => {
    const cases = {
        'missing versions': matrixYaml().replace('- name: listOfE2ETestsSparkVersions', '- name: wrong'),
        'empty versions': matrixYaml([]),
        'duplicate versions': matrixYaml(["'4.0.4'", "'4.0.4'"]),
        'non-patch version': matrixYaml(["'4.0'"]),
        'path-like version': matrixYaml(["'../4.0.4'"]),
        'unquoted first entry': matrixYaml(['4.0.4']),
        'unquoted later entry': matrixYaml(["'4.0.4'", '4.0.5']),
        'malformed later entry': matrixYaml(["'4.0.4'", "version: '4.0.5'"]),
        'missing Linux': matrixYaml(undefined, ["'Windows'"]),
        'duplicate platform': matrixYaml(undefined, ["'Windows'", "'Linux'", "'Linux'"]),
        'extra platform': matrixYaml(undefined, ["'Windows'", "'Linux'", "'macOS'"]),
        'changed platform order': matrixYaml(undefined, ["'Linux'", "'Windows'"]),
        'duplicate parameter': `${matrixYaml()}\n${matrixYaml()}`
    };
    for (const [name, yaml] of Object.entries(cases)) {
        await t.test(name, () => assert.throws(() => readMatrix(yaml)));
    }
});

test('snapshot accepts only checks from the exact Azure app, project, pipeline and SHA', async t => {
    const invalid = {
        'wrong app ID': { app: { ...APP, id: 1 } },
        'wrong app slug': { app: { ...APP, slug: 'other-app' } },
        'missing app': { app: null },
        'wrong SHA': { head_sha: OTHER_SHA },
        'string check ID': { id: '100' },
        'unsafe check ID': { id: Number.MAX_SAFE_INTEGER + 1 },
        'wrong summary name': { name: 'spark.net-other' },
        'wrong project': { external_id: '51729|200|00000000-0000-0000-0000-000000000000' },
        'wrong pipeline': { external_id: `51728|200|${PROJECT}` },
        'missing external ID': { external_id: null },
        'malformed external ID': { external_id: `51729|200|${PROJECT}|extra` },
        'zero build ID': { external_id: `51729|0|${PROJECT}` },
        'negative build ID': { external_id: `51729|-1|${PROJECT}` },
        'unsafe build ID': { external_id: `51729|9007199254740992|${PROJECT}` }
    };
    for (const [name, overrides] of Object.entries(invalid)) {
        await t.test(name, () => {
            const snapshot = createSnapshot(SHA, MATRIX, [check(overrides)]);
            assert.equal(snapshot.buildId, null);
            assert.equal(snapshot.overall.message, 'pending');
            assert.ok(snapshot.jobs.every(lane => lane.message === 'pending'));
        });
    }
    assert.equal(createSnapshot(SHA, MATRIX, [check()]).buildId, 200);
    for (const sha of ['main', '', 'A'.repeat(40), 'a'.repeat(39), `${SHA}/other`]) {
        assert.throws(() => createSnapshot(sha, MATRIX, []), /Invalid source commit/);
    }
});

test('newest build is selected before check ID and does not reuse older green lanes', () => {
    const snapshot = createSnapshot(SHA, MATRIX, [
        check({ id: 900 }, 199),
        job('4.0.4', 'Windows', { id: 999 }, 199),
        job('4.0.4', 'Linux', { id: 998 }, 199),
        check({ id: 10, status: 'queued', conclusion: null }, 200)
    ]);
    assert.equal(snapshot.buildId, 200);
    assert.equal(snapshot.overall.message, 'queued');
    assert.ok(snapshot.jobs.every(lane => lane.message === 'pending' && lane.checkId === null));
});

test('newest check ID wins duplicate reports within a build regardless of API order', () => {
    const reports = [
        check(),
        job('4.0.4', 'Windows', { id: 103, status: 'completed', conclusion: 'success' }),
        job('4.0.4', 'Windows', { id: 101, status: 'queued', conclusion: null }),
        job('4.0.4', 'Windows', { id: 102, status: 'in_progress', conclusion: null })
    ];
    const snapshot = createSnapshot(SHA, MATRIX, reports);
    assert.equal(snapshot.jobs[0].message, 'passing');
    assert.equal(snapshot.jobs[0].checkId, 103);
    assert.deepEqual(snapshot, createSnapshot(SHA, MATRIX, [...reports].reverse()));
});

test('newest build can be discovered before its summary, and missing final jobs are explicit', () => {
    const partial = createSnapshot(SHA, MATRIX, [
        check({}, 199),
        job('4.0.4', 'Linux', {}, 199),
        job('4.0.4', 'Windows', { status: 'in_progress', conclusion: null }, 200)
    ]);
    assert.equal(partial.buildId, 200);
    assert.equal(partial.overall.message, 'pending');
    assert.deepEqual(partial.jobs.map(lane => lane.message), ['running', 'pending']);
    const finished = createSnapshot(SHA, MATRIX, [check({ conclusion: 'failure' })]);
    assert.ok(finished.jobs.every(lane => lane.message === 'not reported'));
});

test('status mapping is explicit and only completed success becomes green', async t => {
    const completed = {
        success: ['passing', '#4c1'], failure: ['failing', '#e05d44'],
        timed_out: ['timed out', '#e05d44'], cancelled: ['cancelled', '#9f9f9f'],
        skipped: ['skipped', '#9f9f9f'], neutral: ['neutral', '#9f9f9f'],
        stale: ['stale', '#9f9f9f'], action_required: ['action required', '#dfb317']
    };
    for (const [conclusion, expected] of Object.entries(completed)) {
        await t.test(`completed ${conclusion}`, () => {
            const state = createSnapshot(SHA, MATRIX, [check({ conclusion })]).overall;
            assert.deepEqual([state.message, state.color], expected);
        });
    }
    const active = {
        queued: ['queued', '#dfb317'], pending: ['pending', '#dfb317'],
        waiting: ['waiting', '#dfb317'], requested: ['requested', '#dfb317'],
        in_progress: ['running', '#007ec6']
    };
    for (const [status, expected] of Object.entries(active)) {
        await t.test(`active ${status} ignores stale success conclusion`, () => {
            const state = createSnapshot(SHA, MATRIX, [check({ status })]).overall;
            assert.deepEqual([state.message, state.color], expected);
        });
    }
    for (const conclusion of [null, undefined, 'unknown', 'queued', 'in_progress']) {
        await t.test(`unknown completed conclusion ${conclusion}`, () => {
            const state = createSnapshot(SHA, MATRIX, [check({ conclusion })]).overall;
            assert.deepEqual([state.message, state.color], ['unknown', '#9f9f9f']);
        });
    }
    for (const status of ['success', 'failure', 'unknown', null]) {
        await t.test(`unknown status ${status}`, () => {
            const state = createSnapshot(SHA, MATRIX, [check({ status })]).overall;
            assert.deepEqual([state.message, state.color], ['unknown', '#9f9f9f']);
        });
    }
});

test('collector uses pagination, filter all, and only Azure suites for main at the source SHA', async () => {
    const matrix = readMatrix(PIPELINE);
    const suite = overrides => ({ id: 10, app: APP, head_branch: 'main', head_sha: SHA, ...overrides });
    const pages = [
        Array.from({ length: 100 }, (_, id) => suite({ id: id + 100, head_branch: 'feature' })),
        [suite(), suite({ id: 11 }), suite({ id: 12, app: { ...APP, id: 2 } }),
            suite({ id: 13, app: { ...APP, slug: 'other' } }), suite({ id: 14, head_sha: OTHER_SHA })]
    ];
    const windows = matrix.versions.map((version, id) => job(version, 'Windows', { id: id + 1000 }));
    const linux = matrix.versions.map((version, id) => job(version, 'Linux', { id: id + 2000 }));
    const listSuitesForRef = Symbol('listSuitesForRef');
    const listForSuite = Symbol('listForSuite');
    const calls = [];
    const github = {
        rest: { checks: { listSuitesForRef, listForSuite } },
        async paginate(method, args) {
            calls.push({ method, args });
            if (method === listSuitesForRef) return pages.flat();
            assert.equal(method, listForSuite);
            assert.ok([10, 11].includes(args.check_suite_id));
            return args.check_suite_id === 10 ? [check(), ...windows] : linux;
        }
    };
    const snapshot = await collectSnapshot(github, SHA, matrix);
    assert.equal(snapshot.jobs.length, 54);
    assert.ok(snapshot.jobs.every(lane => lane.message === 'passing'));
    assert.deepEqual(calls[0].args, {
        owner: 'dotnet', repo: 'spark', ref: SHA, app_id: APP.id, per_page: 100
    });
    assert.deepEqual(calls.slice(1).map(call => call.args), [10, 11].map(id => ({
        owner: 'dotnet', repo: 'spark', check_suite_id: id, filter: 'all', per_page: 100
    })));
});

test('collector propagates API errors instead of fabricating a snapshot', async () => {
    const failure = new Error('GitHub API unavailable');
    const github = {
        rest: { checks: { listSuitesForRef: 'suites' } },
        async paginate() { throw failure; }
    };
    await assert.rejects(collectSnapshot(github, SHA, MATRIX), error => error === failure);
});

test('SVG escapes labels and states, includes source identity, and renders deterministically', () => {
    const snapshot = createSnapshot(SHA, MATRIX, [check()]);
    const state = { message: '<&"\'>', color: '#9f9f9f' };
    const svg = renderBadge('<&"\'>', state, snapshot);
    assert.match(svg, /&lt;&amp;&quot;&apos;&gt;/);
    assert.ok(!svg.includes('<&'));
    assert.ok(svg.includes(`main@${SHA}; build 200`));
    assert.match(svg, /<svg[^>]+role="img"[^>]+aria-label=/);
    assert.match(svg, /<title>/);
    assert.equal(svg, renderBadge('<&"\'>', state, snapshot));
});

test('all 54 lane files and main/revision references match the real README matrix', () => {
    const matrix = readMatrix(PIPELINE);
    const snapshot = createSnapshot(SHA, matrix, []);
    const files = renderFiles(snapshot);
    const readme = readFileSync(path.join(ROOT, 'README.md'), 'utf8');
    const lanePaths = matrix.versions.flatMap(version => matrix.platforms.map(platform =>
        `badges/spark-${version}-${platform.toLowerCase()}.svg`));
    assert.deepEqual(Object.keys(files).filter(file => file.startsWith('badges/spark-')), lanePaths);
    assert.equal(Object.keys(files).length, 59);
    assert.equal(files['.ci-status-owner'], OWNER_MARKER);
    assert.deepEqual(JSON.parse(files['status.json']), snapshot);
    assert.deepEqual(files, renderFiles(createSnapshot(SHA, matrix, [])));
    for (const file of [...lanePaths, 'badges/main.svg', 'badges/revision.svg']) {
        assert.ok(readme.includes(`https://raw.githubusercontent.com/dotnet/spark/ci-status/${file}`),
            `README is missing ${file}`);
    }
    assert.match(readme, /^\[ci-main\]:/m);
    assert.match(readme, /^\[ci-revision\]:/m);
    const rows = [...readme.matchAll(/^\| (\d+\.\d+\.\d+) \|/gm)].map(match => match[1]);
    assert.deepEqual(rows, matrix.versions);
    assert.ok(!files['README.md'].includes('buildId=null'));
});

function publisherMock(options = {}) {
    const calls = [];
    let mainRead = 0;
    function operation(name, response) {
        return async args => {
            assert.equal(args.owner, 'dotnet');
            assert.equal(args.repo, 'spark');
            calls.push({ name, args });
            if (options.failAt === name) throw Object.assign(new Error(`Failure: ${name}`), { status: 503 });
            return { data: await response(args) };
        };
    }
    const github = { rest: {
        git: {
            getRef: operation('getRef', args => {
                if (args.ref === 'heads/main') {
                    const sha = options.mainShas?.[mainRead++] ?? SHA;
                    return { object: { sha } };
                }
                assert.equal(args.ref, 'heads/ci-status');
                if (!options.exists) throw Object.assign(new Error('Not found'), { status: 404 });
                return { object: { sha: 'previous-commit' } };
            }),
            getCommit: operation('getCommit', () => ({ tree: { sha: 'previous-tree' } })),
            createTree: operation('createTree', () => ({ sha: options.unchanged ? 'previous-tree' : 'new-tree' })),
            createCommit: operation('createCommit', () => ({ sha: 'new-commit' })),
            createRef: operation('createRef', () => ({})),
            updateRef: operation('updateRef', () => ({}))
        },
        repos: {
            getContent: operation('getContent', () => ({
                type: 'file', encoding: 'base64',
                content: Buffer.from(options.marker ?? OWNER_MARKER).toString('base64'),
                ...options.markerOverrides
            }))
        }
    } };
    return { github, calls };
}

function mutations(calls) {
    return calls.filter(call => ['createTree', 'createCommit', 'createRef', 'updateRef'].includes(call.name));
}

function publishFixture(mock) {
    const snapshot = createSnapshot(SHA, MATRIX, [check()]);
    return publishSnapshot(mock.github, snapshot, renderFiles(snapshot));
}

test('first publication creates an orphan status branch without touching main', async () => {
    const mock = publisherMock();
    assert.equal(await publishFixture(mock), 'published');
    const tree = mock.calls.find(call => call.name === 'createTree').args;
    assert.ok(!('base_tree' in tree));
    assert.ok(tree.tree.every(file => file.mode === '100644' && file.type === 'blob'));
    const commit = mock.calls.find(call => call.name === 'createCommit').args;
    assert.deepEqual(commit.parents, []);
    assert.equal(commit.tree, 'new-tree');
    assert.deepEqual(mock.calls.find(call => call.name === 'createRef').args, {
        owner: 'dotnet', repo: 'spark', ref: 'refs/heads/ci-status', sha: 'new-commit'
    });
    assert.ok(!mock.calls.some(call => call.name === 'updateRef'));
});

test('owned branch publication preserves ancestry and uses a non-force update', async () => {
    const mock = publisherMock({ exists: true });
    assert.equal(await publishFixture(mock), 'published');
    assert.deepEqual(mock.calls.find(call => call.name === 'getContent').args, {
        owner: 'dotnet', repo: 'spark', path: '.ci-status-owner', ref: 'previous-commit'
    });
    assert.equal(mock.calls.find(call => call.name === 'createTree').args.base_tree, 'previous-tree');
    assert.deepEqual(mock.calls.find(call => call.name === 'createCommit').args.parents, ['previous-commit']);
    assert.deepEqual(mock.calls.find(call => call.name === 'updateRef').args, {
        owner: 'dotnet', repo: 'spark', ref: 'heads/ci-status', sha: 'new-commit', force: false
    });
    assert.ok(!mock.calls.some(call => call.name === 'createRef'));
});

test('identical output does not create a commit or update a ref', async () => {
    const mock = publisherMock({ exists: true, unchanged: true });
    assert.equal(await publishFixture(mock), 'unchanged');
    assert.deepEqual(mutations(mock.calls).map(call => call.name), ['createTree']);
});

test('unowned status branch is rejected before creating git objects', async t => {
    for (const options of [
        { marker: 'human-owned branch' },
        { markerOverrides: { type: 'dir' } },
        { markerOverrides: { encoding: 'utf-8' } }
    ]) {
        await t.test(JSON.stringify(options), async () => {
            const mock = publisherMock({ exists: true, ...options });
            await assert.rejects(publishFixture(mock), /not owned/);
            assert.equal(mutations(mock.calls).length, 0);
        });
    }
});

test('main moving before or after commit creation never updates the publication ref', async t => {
    for (const mainShas of [[OTHER_SHA], [SHA, OTHER_SHA]]) {
        await t.test(`main changed on read ${mainShas.length}`, async () => {
            const mock = publisherMock({ exists: true, mainShas });
            assert.equal(await publishFixture(mock), 'main moved; skipped');
            assert.ok(!mock.calls.some(call => ['createRef', 'updateRef'].includes(call.name)));
            assert.equal(mock.calls.some(call => call.name === 'createCommit'), mainShas.length === 2);
        });
    }
});

test('publication surfaces API failures without falling back to unsafe writes', async t => {
    for (const failAt of ['getRef', 'getContent', 'getCommit', 'createTree', 'createCommit', 'updateRef', 'createRef']) {
        await t.test(failAt, async () => {
            const mock = publisherMock({ exists: failAt !== 'createRef', failAt });
            await assert.rejects(publishFixture(mock), new RegExp(`Failure: ${failAt}`));
            assert.equal(mock.calls.at(-1).name, failAt);
            assert.ok(!mock.calls.some(call => call.args.force === true));
        });
    }
});

test('entry point refuses forks, feature branches and PR refs before accessing GitHub', async () => {
    for (const context of [
        { repo: { owner: 'someone', repo: 'spark' }, ref: 'refs/heads/main' },
        { repo: { owner: 'dotnet', repo: 'other' }, ref: 'refs/heads/main' },
        { repo: { owner: 'dotnet', repo: 'spark' }, ref: 'refs/heads/feature' },
        { repo: { owner: 'dotnet', repo: 'spark' }, ref: 'refs/pull/123/merge' }
    ]) {
        await assert.rejects(run({ github: {}, context, core: {}, sourceSha: SHA }), /restricted/);
    }
});

test('entry point skips a checkout that is no longer main without collecting or publishing', async () => {
    const mock = publisherMock({ mainShas: [OTHER_SHA] });
    const notices = [];
    await run({
        github: mock.github,
        context: { repo: { owner: 'dotnet', repo: 'spark' }, ref: 'refs/heads/main' },
        core: { notice: message => notices.push(message) }, sourceSha: SHA
    });
    assert.equal(notices.length, 1);
    assert.match(notices[0], /Main moved/);
    assert.deepEqual(mock.calls.map(call => call.name), ['getRef']);
});
