<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;net8.0</TargetFrameworks>
    <RootNamespace>Microsoft.Spark.UnitTest</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq" Version="4.20.70" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microsoft.Spark\Microsoft.Spark.csproj" />
  </ItemGroup>

  <Choose>
    <When Condition="'$(TargetFramework)' == 'net472'">
      <ItemGroup>
        <!-- System.Runtime.Loader.AssemblyLoadContext is .NET Core only -->
        <Compile Remove="AssemblyLoaderTests.cs" />
      </ItemGroup>
    </When>
  </Choose>

</Project>
